package org.motechproject.appointments.domain;

import org.joda.time.DateTime;
import org.joda.time.Period;

import java.util.Map;

/**
 * Appointment class to track the appointments of a person with a given external Id
 */
public class Appointment {

    // External id set by the implementation
    private String externalId;

    // Appointment id generated by the system
    private String id;

    // Due date for the appointment
    private DateTime dueDate;

    // Date of the fulfilled visit
    private DateTime visitedDate;

    // Status flag to indicate if the appointment was missed
    private AppointmentStatus status;

    // Flag to activate or deactivate sending reminders
    private boolean sendReminders;

    // Reminder interval in seconds
    private Period reminderInterval;

    // Time to start firing the reminder events
    private DateTime reminderStartTime;
}
